Repository Randmar-io/rampui, pull requests merged in 2024-02, with the labels that each got.

#7 V0.8.10
  .github/workflows/publish.yml
  package-lock.json
  package.json
Labels: release

#8 Update package.json
  package.json
Labels: release

#9 Update publish.yml
  .github/workflows/publish.yml
Labels: release

#10 Update package.json
  package.json
Labels: release

#11 Update package.json
  package.json
Labels: release

#12 Update package.json
  package.json
Labels: release

#13 Update package.json
  package.json
Labels: release

#15 Update package.json
  package.json
Labels: release

#16 Update package.json
  package.json
Labels: release

#17 Update package.json
  package.json
Labels: release

#18 Update package.json
  package.json
Labels: release

#19 0.9.3
  package-lock.json
  package.json
Labels: release

#21 0.9.6
  package-lock.json
  package.json
Labels: release

#22 0.9.8
  package-lock.json
  package.json
Labels: release

#24 Styles fix
  .babelrc
  package-lock.json
  package.json
  src/AppShell/AppShell.tsx
  src/Provider/Provider.css
  src/Provider/Provider.tsx
  src/index.css
  src/tokens/border.css
  src/tokens/border.ts
  src/tokens/height.css
  src/tokens/height.ts
  src/tokens/index.ts
  src/tokens/shadow.css
  src/tokens/shadow.ts
  src/tokens/spacing.css
  src/tokens/spacing.ts
  src/tokens/width.css
  src/tokens/width.ts
  vite.config.js
Labels: release

#25 Remove references to index.css
  .github/workflows/publish.yml
  src/index.ts
Labels: release

#26 Handle versioning in publish.yml
  .github/workflows/publish.yml
  package.json
Labels: release-patch

#27 Edit publish.yml
  .github/workflows/publish.yml
Labels: release-patch

#30 Workflow
  .github/workflows/publish.yml
Labels: release-patch

#31 Update publish.yml
  .github/workflows/publish.yml
Labels: release-patch

#32 Update publish.yml
  .github/workflows/publish.yml
Labels: release-patch

#33 Update publish.yml
  .github/workflows/publish.yml
Labels: release-patch

#34 Add git credentials
  .github/workflows/publish.yml
Labels: release-patch

#35 Update publish.yml
  .github/workflows/publish.yml
Labels: release-patch

#36 Update publish.yml
  .github/workflows/publish.yml
Labels: release-patch

#37 f
  .github/workflows/publish.yml
Labels: release-minor

#39 Add theme prop to Provider
  src/ExpandPanelIcon/ExpandPanelIcon.tsx
  src/ProductInventoryGrid/ProductInventoryGrid.tsx
  src/Provider/Provider.tsx
Labels: release-minor

#41 add prop to hide bin
  src/ProductInventoryGrid/ProductInventoryGrid.tsx
Labels: release-minor

#42 For pipeline testing
  src/Provider/theme.ts
Labels: release-patch

#43 Theming
  src/AppShell/TopBar/TopBar.tsx
  src/Button/Button.stories.tsx
  src/Button/Button.tsx
  src/Button/styles/buttonStyles.ts
  src/Education/components/Content.tsx
  src/ExpandPanelIcon/ExpandPanelIcon.tsx
  src/ProductInventoryGrid/ProductInventoryGrid.tsx
  src/Provider/Provider.tsx
  src/Provider/theme.ts
  src/colors/randmar.ts
  src/colors/red.ts
Labels: release-major

#44 Revert release
  package.json
Labels: release-minor

#46 Fix renaming of icon prop in Button
  src/Button/Button.tsx
Labels: release-patch

#47 Hide elements if not provided in Education
  src/Education/components/Content.tsx
Labels: release-patch

#48 Spell change
  README.md
Labels: release-patch

#49 Update colors
  src/AppShell/AppShell.stories.tsx
  src/AppShell/TopBar/TopBar.tsx
  src/Button/ButtonBase.tsx
  src/Education/components/Activator.tsx
  src/Provider/Provider.tsx
  src/colors/blue.ts
  src/colors/purple.ts
  src/colors/red.ts
Labels: release-patch

#50 Modify red color shades
  src/colors/red.ts
Labels: release-patch

#51 Add Preloader component
  package-lock.json
  package.json
  src/Preloader/Preloader.stories.tsx
  src/Preloader/Preloader.tsx
  src/Preloader/assets/PreloaderIcon.tsx
  src/Preloader/assets/animations/LoadingIconBlack.json
  src/Preloader/assets/animations/LoadingIconBlue.json
  src/Preloader/assets/animations/LoadingIconPurple.json
  src/Preloader/assets/animations/LoadingIconRed.json
  src/Preloader/assets/animations/LoadingIconWhite.json
  src/Preloader/index.ts
  src/index.ts
  tsconfig.json
Labels: release-minor

#52 Dynamic theme colors for all components
  .storybook/preview.jsx
  src/AppShell/TopBar/TopBar.tsx
  src/Button/ButtonBase.tsx
  src/Education/components/Activator.tsx
  src/Education/components/Content.tsx
  src/NavMenu/NavLink/NavLink.tsx
  src/Preloader/Preloader.tsx
  src/Provider/Provider.tsx
  src/Provider/theme.ts
Labels: release-patch
